export const URL = 'https://api.brawlapi.com/v1/brawlers'
export const RARITY = 'Rarity'
export const CLASS = 'Class'
export const ALL = 'All'
export const PREV = 'prev'
export const NEXT = 'next'
export const FIRST_BRAWLER_ID = '16000000'
export const LAST_BRAWLER_ID = '16000077'
